-----------------------------------------------------
Update von RHEL3-U2-x86_64 auf RHEL3-U4-x86_64 mittels
./pyrpmyum -v --test -c ../../yrsc/rhel3-u4-x86_64.conf -r /mnt/data/karsten-rhel3-u2-x86_64 update

ergibt:
Dependency iteration 4
Resolving dependencies for openoffice.org-0:1.1.0-16.14.EL.i386
runDepRes() took 25.69 seconds
Error: libungif-4.1.0-15.x86_64 conflicts with:
Error:  libungif-0:4.1.0-15.i386
Error: libungif-0:4.1.0-15.i386 conflicts with:
Error:  libungif-4.1.0-15.x86_64
Error: librsvg2-0:2.2.3-6.x86_64 conflicts with:
Error:  gtk2-2.2.4-4.0.i386
#ls ls /mnt/data/karsten-rhel3-u2-x86_64/var/lib/pyrpm/headers/libung*
/mnt/data/karsten-rhel3-u2-x86_64/var/lib/pyrpm/headers/libungif-4.1.0-15.x86_64  /mnt/data/karsten-rhel3-u2-x86_64/var/lib/pyrpm/headers/libungif-devel-4.1.0-15.x86_64

same run with -vvv:
runDepRes() took 26.4 seconds
Error: libungif-4.1.0-15.x86_64 conflicts with:
Error:  'giflib' <=> libungif-0:4.1.0-15.i386
Error: libungif-0:4.1.0-15.i386 conflicts with:
Error:  'giflib' <=> libungif-4.1.0-15.x86_64
Error: librsvg2-0:2.2.3-6.x86_64 conflicts with:
Error:  'gtk2 < 0:2.2.4-9' <=> gtk2-2.2.4-4.0.i386
-----------------------------------------------------

./pyrpmyum -y --autoerase --servicehack --quiet --test --fileconflicts --ignoresize -r /mnt/build/laroche/FC3-installtest-x86_64 -c /mnt/build/laroche/FC3-installtest-x86_64/etc/yum.conf install *
processArgs() took 0.42 seconds
Traceback (most recent call last):
  File "./pyrpmyum", line 259, in ?
    main()
  File "./pyrpmyum", line 237, in main
    yum.runDepRes()
  File "../pyrpm/yum.py", line 157, in runDepRes
    self.__runDepResolution()
  File "../pyrpm/yum.py", line 321, in __runDepResolution
    self.__handleConflictAutoerases()
  File "../pyrpm/yum.py", line 365, in __handleConflictAutoerases
    conflicts = self.opresolver.getFileConflicts()
  File "../pyrpm/resolver.py", line 383, in getFileConflicts
    if S_ISDIR(fi1.mode) and S_ISDIR(fi2.mode):
  File "/usr/lib64/python2.4/stat.py", line 46, in S_ISDIR
    return S_IFMT(mode) == S_IFDIR
  File "/usr/lib64/python2.4/stat.py", line 30, in S_IFMT
    return mode & 0170000
TypeError: unsupported operand type(s) for &: 'NoneType' and 'int'


-----------------------------------------------------
